server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:orderdb
    username: sa
    password:

resilience4j:
  retry:
    instances:
      userService:
        maxAttempts: 3
        waitDuration: 5s
