server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ipaddress: localhost


management:
  tracing:
    sampling:
      probability: 1.0   # trace every request

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
